#端口配置
server:
  url: 10.133.31.63
  port: 8999
app:
  id: wxb35202144a522b5a
  secret: 61a8858eb3538fd6803677dca4bf96ef

#Mysql连接池
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://114.132.44.9:3306/govaffairs?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true

#mybatis-plus SQL输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志打印
logging:
  config: classpath:logback-spring.xml

#存放路径
absoluteImgPath: D:/images_zhihuicuiwu
sonImgPath: /images/



